backend:
  replicaCount: 2
  repository: "surendergupta/learnercs_be:latest"
  pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  service:
    type: LoadBalancer
    port: 80
    targetPort: 5000

frontend:
  replicaCount: 1
  repository: "surendergupta/learnercs_fe:latest"
  pullPolicy: Always

  service:
    type: LoadBalancer
    port: 80
    targetPort: 3000