apiVersion: v1
kind: Service
metadata:
  name: {{ include "container-orchestration-chart.fullname" . }}-learnercs-be-svc
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: learnercs-be
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}