apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "container-orchestration-chart.fullname" . }}-learnercs-be-ingress
spec:
  rules:
    - host: hello.cloudcrypto.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "container-orchestration-chart.fullname" . }}-learnercs-be
                port:
                  number: 80
