apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "container-orchestration-chart.fullname" . }}-learnercs-be-pod
  labels:
    app: learnercs-be
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: learnercs-be
  template:
    metadata:
      labels:
        app: learnercs-be
    spec:
      containers:
      - name: learnercs-be
        image: {{ .Values.backend.repository }}
        imagePullPolicy: {{ .Values.backend.pullPolicy }}
        resources:
          requests:
            memory: {{ .Values.backend.resources.requests.memory }}
          limits:
            memory: {{ .Values.backend.resources.limits.memory }}        
            cpu: {{ .Values.backend.resources.limits.cpu }}
        ports:
        - containerPort: {{ .Values.backend.service.targetPort }}