apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "container-orchestration-chart.fullname" . }}-learnercs-fe-pod
  labels:
    app: learnercs-fe
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: learnercs-fe
  template:
    metadata:
      labels:
        app: learnercs-fe
    spec:
      containers:
      - name: learnercs-fe
        image: {{ .Values.frontend.repository }}
        imagePullPolicy: {{ .Values.frontend.pullPolicy }}        
        ports:
        - containerPort: {{ .Values.frontend.service.targetPort }}