apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "container-orchestration-chart.fullname" . }}-learnercs-fe-ingress
spec:
  rules:
    - host: {{ .Values.frontend.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: learnercs-fe
                port:
                  number: 80
