apiVersion: v1
kind: Service
metadata:
  name: {{ include "container-orchestration-chart.fullname" . }}-learnercs-fe-svc
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: learnercs-fe
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}